mongodb/motor

motor/core.py, motor/frameworks/asyncio.py, motor/frameworks/tornado.py, motor/motor_common.py, setup.py, test/__init__.py, test/asyncio_tests/__init__.py, test/asyncio_tests/test_asyncio_basic.py, test/asyncio_tests/test_asyncio_client.py, test/asyncio_tests/test_asyncio_collection.py, test/asyncio_tests/test_asyncio_cursor.py, test/asyncio_tests/test_asyncio_database.py, test/asyncio_tests/test_asyncio_gridfs.py, test/asyncio_tests/test_asyncio_ipv6.py, test/asyncio_tests/test_asyncio_pool.py, test/asyncio_tests/test_asyncio_son_manipulator.py, test/asyncio_tests/test_asyncio_ssl.py, test/asyncio_tests/test_asyncio_tail.py, test/asyncio_tests/test_asyncio_tests.py, test/test_environment.py, test/test_motor_collection.py
=> asyncio integration

doc/examples/callbacks-and-coroutines.rst
Hi, the callback keyword was not present in the example.
=> added *callback* keyword to example

motor/core.py
Line 368-371 is duplicated with line 364-367.
Note that there is still problem that `_closed()` will always return `False` in `asyncio` framework because `AsyncioMotorSocket.fileno()` is not implemented.
=> Remove redundancy code.

README.rst, doc/index.rst, doc/tutorial-asyncio.rst, tox.ini
As per [their blog post of the 27th April](https://blog.readthedocs.com/securing-subdomains/) ‘Securing subdomains’:
> Starting today, Read the Docs will start hosting projects from subdomains on the domain readthedocs.io, instead of on readthedocs.org. This change addresses some security concerns around site cookies while hosting user generated data on the same domain as our dashboard.
Test Plan: Manually visited all the links I’ve modified.
=> Convert readthedocs link for their .org -> .io migration for hosted projects

motor/core.py
After wondering why Python 3.5 aggregate example was printing `None`s, I figured out that it had an extra line that was wrong.
=> Fix Python 3.5 aggregate example

doc/motor_extensions.py
The regexp `sub()` method doesn't take flags as an argument.
The flags have to be supplied at compile time, and another part of code already does that.
=> Fix incorrect use of regexp flags

motor/core.py, test/tornado_tests/test_motor_cursor.py
AgnosticCursor::collation can't be called as chained method
```python
db["test_collection"].find({}).sort("field").collation(Collation("pl")).to_list(length=1)
```
This PR resolves bug https://jira.mongodb.org/browse/MOTOR-154
=> allow AgnosticCursor.collation to be called as chained method

motor/docstrings.py
By default, operations are only casually consistent within the same session. The `insert` must use the same session as the `find`.
=> Fix causal consistency example.

motor/core.py
I found a sample error on the motor.readthedocs.io, then I fixed the sample document
=> fix: fix sample document

test/asyncio_tests/test_asyncio_tests.py
This fixes running tests with Python 3.8
=> tests: Expect asyncio.exceptions.TimeoutError where it is present

motor/core.py, motor/frameworks/asyncio/__init__.py, motor/frameworks/tornado/__init__.py, test/asyncio_tests/__init__.py, test/asyncio_tests/test_asyncio_cursor.py, test/utils.py
This change prevents Motor from failing with `asyncio.exceptions.InvalidStateError: invalid state` when tasks are cancelled by the application.
=> MOTOR-488 Don't call set_result on a cancelled tasks

README.rst, doc/index.rst, doc/installation.rst
I made changes to make the Readme and documentation index page consistent with that of PyMongo - I think this will make it more maintainable in the long run. If you don't share this opinion, I can make surgical changes and leave in place the old language and structure.
=> MOTOR-538 Revise issues and help sections of documentation

motor/core.py, test/asyncio_tests/test_asyncio_change_stream.py
This change makes motor's ChangeStream work more like PyMongo's by establishing the server-side cursor earlier. PyMongo creates the cursor in the call to `watch()`. To do that in Motor we would need to make `watch` async  (`def watch(...)` -> `async def watch(...)`) which is a backward breaking change. Instead, Prashant had the clever idea to create the cursor in `__aenter__`. This will resolve the user's complaint in https://jira.mongodb.org/browse/MOTOR-320.
=> MOTOR-320 Create ChangeStream cursor in async with __aenter__

motor/docstrings.py
The changes to bulk propagate without anything required in Motor because Operation classes are not re-implemented in Motor.
Also addresses:
MOTOR-455 Allow hinting the findAndModify commands
MOTOR-433 Allow hinting the update command
=> MOTOR-505 Allow hinting the delete command

motor/__init__.py, setup.py
Ignore the branch name - I followed what was done in https://github.com/mongodb/motor/commit/dad11a56537e0282c9b91d38a86a3b8adb817388 and bumped the minor version instead of the patch version.
=> BUMP 2.3.0.dev0

motor/frameworks/asyncio/__init__.py, motor/frameworks/tornado/__init__.py
Add support to context vars.
This may be useful for logging, e.g. pass trace params like request_id to CommandLogger
=> MOTOR-613: Add contextvars support

doc/changelog.rst, doc/contributors.rst, test/asyncio_tests/test_asyncio_client.py
Added a test case inspired by the example in https://github.com/mongodb/motor/pull/88.
=> MOTOR-613 Test contextvars support

doc/api-asyncio/asyncio_motor_client_encryption.rst, doc/examples/auto_csfle_example.py, doc/examples/encryption.rst, doc/examples/explicit_encryption_automatic_decryption_example.py, doc/examples/explicit_encryption_example.py, doc/examples/jsonSchema.json, doc/examples/server_fle_enforcement_example.py
Ported over examples for explicit encryption/decryption from PyMongo CSFLE. Built docs to check that they render correctly and ran each example to ensure that they work as expected.
=> MOTOR-476: Update FLE documentation for community version demonstrating explicit encryption/decryption

.evergreen/config.yml, .travis.yml, setup.py, tox.ini
Run Test suite on Python 3.9, add Python 3.9 to evergreen test matrix and travis builds
=> MOTOR-622: Add Python 3.9 support

.eggs/README.txt, test/asyncio_tests/test_asyncio_encryption.py
Older versions of MDB do not support CSFLE, so require 4.2 version to run tests
=> MOTOR-701: Require MongoDB 4.2+ to run CSFLE tests

.evergreen/config.yml, tox.ini
We must override the PyMongo dependency as part of [tox commands](https://tox.readthedocs.io/en/latest/index.html#system-overview) to ensure the version specified in `install_requires` doesn't prevail. The `#egg=pymongo[encryption]` is required to pull in the `encryption` extra with the `pip git+` syntax.
=> MOTOR-703 Ensure we are testing against latest pymongo v3.12 commit

doc/examples/monitoring.rst
- Corrects name of Python file for the monitoring example
=> (docs) fix broken link

doc/conf.py
autodoc_default_flags has been deprecated since version 1.8. We need to use autodoc_default_options instead. See:
- https://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html#confval-autodoc_default_flags
- https://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html#confval-autodoc_default_options
=> MOTOR-794 Fix support for Sphinx 4

test/asyncio_tests/test_examples.py
This is a weird one. Somehow we are supposed to show the output of running some commands as part of the example. I am not really sure how to do that...
=> MOTOR-784 Versioned API migration example for ecosystem docs

motor/core.py, test/asyncio_tests/test_asyncio_cursor.py
1. Fix that the number of query results is inconsistent with the length argument when calling to_list().
2. Adding a test case named "A" to cover this case.
=> MOTOR-805 Fix that the number of query results is inconsistent with the length argument when calling to_list().

test/asyncio_tests/test_asyncio_change_stream.py, test/tornado_tests/test_motor_change_stream.py
See the explanation in https://jira.mongodb.org/browse/MOTOR-808
=> MOTOR-808 Fix test_watch_with_start_after on MongoDB 5.1+

README.rst, doc/contributors.rst, doc/installation.rst, setup.py
Motor is a wrapper around Pymongo, extras available during pip install Pymongo should be available with Motor as well. I recently faced an issue regarding this and have raised it on Jira.
=> MOTOR-884 Mirror all PyMongo extras

motor/core.py, motor/docstrings.py
Some of these were added as part of #158
=> MOTOR-843 Add support for the comment field to all helpers

motor/frameworks/asyncio/__init__.py
…issued
It looks like a workaround I wrote in Tornado was incorrectly incorporated into AsyncioMotorClient here https://github.com/mongodb/motor/pull/155/files#r851429040
if a user has opted into DeprecationWarnings as errors `asyncio.get_event_loop_policy().get_event_loop()` incorrectly suppresses the deprecation warning: 
``` graingert@superjacent  testing310  ~  python3.10 -Werror
Python 3.10.4 (main, Apr  8 2022, 17:35:13) [GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import motor.motor_asyncio
>>> client = motor.motor_asyncio.AsyncIOMotorClient()
>>> client.test.pages.drop()  # this should raise a DeprecationWarning because it was called without a running loop
<Future pending cb=[_chain_future.<locals>._call_check_cancel() at …
```
=> MOTOR-979 Use asyncio.get_event_loop so that DeprecationWarnings are correctly issued

motor/core.py, test/asyncio_tests/test_asyncio_cursor.py
When I use the following code:
```python
async with self.coll.find() as cursor:
async for record in cursor:
yield record
```
It's going to throw an AttributeError
So I added the asynchronous context manager method
so that I did not have to close the cursor when I was done with it
=> MOTOR-1014 Add __aenter__ and __aexit__ for AgnosticBaseCursor so that cursor can be instantiated using the context manager

test/asyncio_tests/test_asyncio_encryption.py, test/test_environment.py
Fix https://jira.mongodb.org/browse/MOTOR-1025. 
Also fixes a uuid expectation bug in the tests.
=> MOTOR-1025 Fix test_asyncio_encryption

doc/examples/aiohttp_example.py
Hi,
For a newbie to motor and asyncio the code proposed here would not work especially for python3.9 onwards. asyncio automatically closes the event loop at the end of asyncio.run() method. Subsequently the aiohttp is not able to open new event loop[issue is faced on all platforms: windows, linux, mac_os]. Proposed are the changes works and ensures that the event loop is consistent among aiohttp and motor's event loop
=> Update aiohttp example

synchro/synchrotest.py, test/asyncio_tests/test_asyncio_collection.py, test/asyncio_tests/test_examples.py, test/test_environment.py, test/tornado_tests/test_motor_collection.py
Resolves https://jira.mongodb.org/browse/MOTOR-1098
=> MOTOR-1098 Skip synchro test_typing and encrypted coll tests on standalones

pyproject.toml
Our tests break when we leverage `aiohttp>=3.8.6` tests will fail.
=> PYTHON-4040 Pin testing to aiohttp<3.8.6

.github/workflows/release.yml, RELEASE.rst
Based on https://github.com/pypa/wheel/blob/main/.github/workflows/publish.yml
=> MOTOR-1219 Use PyPI Trusted Publishing

motor/core.pyi
This is what `pymongo` has :)
https://github.com/mongodb/mongo-python-driver/blob/8f7b86f3f39c31981cd860313c1141bce88ade26/pymongo/change_stream.py#L274
=> MOTOR-1298 Type `resume_token` as a property

synchro/__init__.py
Fixes:
```
FAILED test/test_logger.py::TestLogger::test_logging_without_listeners - AttributeError: MotorClient has no attribute '_event_listeners'. To access the _event_listeners database, use client['_event_listeners'].
```
=> PYTHON-4499 Fix test_logging_without_listeners

.github/workflows/release.yml
=> PYTHON-5047 Fix dry run logic in releases yet again

doc/contributors.rst, doc/tutorial-asyncio.rst, doc/tutorial-tornado.rst
This is a super easy and common pitfall so it should be made extra obvious
=> [DOCS] make an explicit warning not to create clients for each request
