motor/frameworks/asyncio.py, test/asyncio_tests/test_asyncio_client.py
In case mongo sever goes down, StreamReader raises IncompleteReadError, when should just throw AutoReconnect.
In fix we just return ``b''`` so pymongo raises ``AutoReconnect`` for us, see:
https://github.com/mongodb/mongo-python-driver/blob/414250b5ef918656427e1a60fbf203bd023d543b/pymongo/network.py#L121-L131
@asvetlov @ajdavis  review please.
=> raise AutoReconnect instead of IncompleteReadError

motor/core.py, setup.py, test/asyncio_tests/test_asyncio_await.py, test/asyncio_tests/test_asyncio_client.py, test/test_environment.py, test/tornado_tests/test_motor_await.py, test/tornado_tests/test_motor_client.py, tox.ini
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mongodb/motor/23)
=> Support async / await

doc/conf.py, doc/examples/aiohttp_example.py, doc/tutorial-asyncio.rst
@asvetlov, thanks to you and @jettify, Motor 0.5 with asyncio is close to release. Could you review this example application that I plan to include in the tutorial?
The docs are rendered here:
http://emptysqua.re/aiotthp-example-docs/tutorial-asyncio.html#a-web-application-with-aiohttp
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mongodb/motor/22)
=> MOTOR-40 Example using aiohttp.

motor/__init__.py
As title says. Pretty much nothing changes.
=> Don't hardcode pymongo version in string

test/asyncio_tests/test_asyncio_change_stream.py, test/asyncio_tests/test_asyncio_client.py, test/tornado_tests/test_motor_change_stream.py
Closes https://jira.mongodb.org/browse/MOTOR-377
Closes https://jira.mongodb.org/browse/MOTOR-379
=> MOTOR-377 + MOTOR-379

motor/core.py
Closes https://jira.mongodb.org/browse/MOTOR-391
=> MOTOR-391 Add retry_reads attribute to MotorClient

motor/core.py
Closes https://jira.mongodb.org/browse/MOTOR-318
=> MOTOR-318 Document support for readConcern majority in aggregate with $out

motor/frameworks/asyncio/__init__.py
=> MOTOR-577 Record framework as asyncio

motor/core.py, motor/motor_gridfs.py
I also refactored the GridFS cursor class to be written similar to how it is in PyMongo.
=> MOTOR-454 Support for allowDiskUse in find() commands

.evergreen/config.yml
New tests pass: https://evergreen.mongodb.com/version/5f2d90ba0ae6067b7a820646?redirect_spruce_users=true
=> MOTOR-496 Use windows-64-vsMulti-small and test asyncio on Windows

motor/frameworks/asyncio/__init__.py, setup.py, test/asyncio_tests/__init__.py, test/asyncio_tests/test_aiohttp_gridfs.py, test/asyncio_tests/test_asyncio_client.py, test/asyncio_tests/test_asyncio_collection.py, test/asyncio_tests/test_asyncio_cursor.py, test/asyncio_tests/test_asyncio_tests.py, test/test_environment.py, test/tornado_tests/__init__.py, test/tornado_tests/test_motor_web.py
Jira: https://jira.mongodb.org/browse/MOTOR-597
=> MOTOR-597 Stop using deprecated loop arguments and other improvements

motor/frameworks/asyncio/__init__.py, test/asyncio_tests/test_asyncio_grid_file.py
https://jira.mongodb.org/browse/MOTOR-600
=> MOTOR-600 Fix AsyncIOMotorGridOut.open

motor/core.py, motor/docstrings.py
=> MOTOR-598 Fix doctests and vendor docstrings with code examples

doc/api-asyncio/cursors.rst, doc/api-tornado/cursors.rst, doc/api-tornado/gridfs.rst, doc/api-tornado/motor_collection.rst, doc/differences.rst, doc/examples/bulk.rst, doc/motor_extensions.py, motor/core.py, tox.ini
This will be easier to review after we merge #80
=> MOTOR-420 Remove legacy APIs/patterns from documentation

doc/changelog.rst, motor/__init__.py, setup.py
Please ignore the misnamed branch.
=> BUMP 2.3.1

.readthedocs.yaml, doc/docs-requirements.txt
See https://docs.readthedocs.io/en/stable/guides/reproducible-builds.html#using-a-configuration-file
=> MOTOR-771 Use Sphinx 4 on motor.readthedocs.io

test/asyncio_tests/test_aiohttp_gridfs.py, test/tornado_tests/test_motor_web.py
See https://bugs.python.org/issue43975.
=> MOTOR-730 Stop testing problematic .js content type

motor/core.py
MOTOR-654 Document $out/$merge usage for aggregate
=> MOTOR-745 Document let option for aggregate

.pre-commit-config.yaml, README.rst, doc/contributors.rst, doc/installation.rst, setup.py
(cherry picked from commit 64fbc83)
=> MOTOR-884 [v2.5] Mirror all PyMongo extras

tox.ini
(cherry picked from commit 276f93e0d09d57a61f9743b6bb8b64cbb0392916)
=> MOTOR-906 [v2.5] Doc Build and Test are Failing

synchro/__init__.py
https://jira.mongodb.org/browse/MOTOR-1214
=> MOTOR-1214 Ignore IOLoop.current deprecation to make synchro pass

test/tornado_tests/test_motor_client.py
https://jira.mongodb.org/browse/MOTOR-1182
=> MOTOR-1182 Attach an error code to workaround PYTHON-4038

synchro/synchrotest.py
https://jira.mongodb.org/browse/MOTOR-1216
=> MOTOR-1216 Skip change stream test_concurrent_close tests

README.md, pyproject.toml
Also updates the Project [URLs](https://packaging.python.org/en/latest/guides/writing-pyproject-toml/#urls) that will be rendered on PyPI since we're removing a couple links from the readme.
=> MOTOR-1225 Add badges to README

synchro/__init__.py, synchro/synchrotest.py
=> MOTOR-1240 Skip GridFS tests failing due to PYTHON-4146

motor/docstrings.py
https://jira.mongodb.org/browse/MOTOR-1282
=> MOTOR-1282 Stop using filemd5 in docs example for db.command

synchro/synchrotest.py
=> [MOTOR-1269] Exclude Synchro test TestUnifiedInterruptInUsePoolClear

.github/CODEOWNERS
=> Revert "MOTOR-1294 Reinstate CODEOWNERS file"

doc/changelog.rst
We have more features to add for 8.0 support.
=> MOTOR-1332 Update changelog for 3.5

motor/core.py, motor/core.pyi, synchro/__init__.py, test/tornado_tests/test_motor_core.py
Docs are expected to fail until [MOTOR-1351](https://jira.mongodb.org/browse/MOTOR-1351).
=> MOTOR-940 Improved Bulk Write API

.evergreen/config.yml
Also removes unused functions that would have required elevated permissions.
=> DEVPROD-11430 Use temporary aws creds for s3 uploads

test/asyncio_tests/test_aiohttp_gridfs.py
Passing build: https://spruce.mongodb.com/version/68e5006992de350007380818/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
=> MOTOR-1477 Add workaround for missing compression.zstd
